import { StyleSheet  } from "react-native";

export const styles = StyleSheet.create({
    scrollView: {
        flex: 1,
        backgroundColor: '#f4f6f8',
    },
    contentContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    header: {
        backgroundColor: '#f5f5f5',
        padding: 20,
        borderRadius: 10,
        alignItems: 'center',
        marginBottom: 40,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
    },
    subtitle: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginTop: 10,
        opacity: 0.8,
    },
    footer: {
        fontSize: 12,
        color: '#999',
        textAlign: 'center',
        marginTop: 40,
    },
     container: { backgroundColor: "#f4f6f8", flex: 1 },
  card: {
    margin: 20,
    backgroundColor: "white",
    padding: 20,
    borderRadius: 12,
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  heading: {
    color: "#0d6efd",
    textAlign: "center",
    fontSize: 22,
    marginBottom: 20,
  },
  balance: { fontSize: 18, textAlign: "center" },
  row: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 20,
  },
  label: { color: "#777", textAlign: "center" },
  income: { color: "green", fontSize: 20, textAlign: "center" },
  expenses: { color: "red", fontSize: 20, textAlign: "center" },
  form: { marginBottom: 20 },
  input: {
    backgroundColor: "#eee",
    padding: 12,
    borderRadius: 8,
    marginVertical: 6,
  },
  typeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  typeButton: {
    flex: 1,
    backgroundColor: "#ccc",
    padding: 12,
    borderRadius: 8,
    marginHorizontal: 4,
  },
  activeType: {
    backgroundColor: "#0d6efd",
  },
  typeText: { color: "white", textAlign: "center" },
  addBtn: {
    backgroundColor: "navy",
    padding: 12,
    borderRadius: 8,
    marginTop: 6,
  },
  addText: { color: "white", textAlign: "center", fontSize: 16 },
  txTitle: { fontSize: 18, color: "#555", marginTop: 10 },
  empty: {
    textAlign: "center",
    color: "#888",
    marginVertical: 20,
  },
  txItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
});