import { StyleSheet  } from "react-native";

export const styles = StyleSheet.create({
    scrollView: {
        flex: 1,
        backgroundColor: '#f4f6f8',
    },
    contentContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    header: {
        backgroundColor: '#f5f5f5',
        padding: 20,
        borderRadius: 10,
        alignItems: 'center',
        marginBottom: 40,
    },
     title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
    subtitle: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginTop: 10,
        opacity: 0.8,
    },
    footer: {
        fontSize: 12,
        color: '#999',
        textAlign: 'center',
        marginTop: 40,
    },
     container: { backgroundColor: "#f4f6f8", flex: 1 },
  card: {
    margin: 20,
    backgroundColor: "white",
    padding: 20,
    borderRadius: 12,
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  heading: {
    color: "#0d6efd",
    textAlign: "center",
    fontSize: 22,
    marginBottom: 20,
  },
  balance: { fontSize: 18, textAlign: "center" },
  row: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 20,
  },
  label: { color: "#777", textAlign: "center" },
  income: { color: "green", fontSize: 20, textAlign: "center" },
  expenses: { color: "red", fontSize: 20, textAlign: "center" },
  form: { marginBottom: 20 },
  input: {
    backgroundColor: "#eee",
    padding: 12,
    borderRadius: 8,
    marginVertical: 6,
  },
  typeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  typeButton: {
    flex: 1,
    backgroundColor: "#ccc",
    padding: 12,
    borderRadius: 8,
    marginHorizontal: 4,
  },
  activeType: {
    backgroundColor: "#0d6efd",
  },
  typeText: { color: "white", textAlign: "center" },
  addBtn: {
    backgroundColor: "navy",
    padding: 12,
    borderRadius: 8,
    marginTop: 6,
  },
  addText: { color: "white", textAlign: "center", fontSize: 16 },
  txTitle: { fontSize: 18, color: "#555", marginTop: 10 },
  empty: {
    textAlign: "center",
    color: "#888",
    marginVertical: 20,
  },
  txItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
   navBar: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: "center",
        padding: 12,
        backgroundColor: '#f5f5f5',
        borderRadius: 10,
        width: "100%",
        marginBottom: 25,
    },
    link: {
        fontSize: 18,
        color: '#007AFF',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 15,
    },
    activeLink: {
        fontWeight: 'bold',
        backgroundColor: '#e0e0e0',
        color: '#000',
    },
    /* Calendar specific styles */
    calendarCard: {
      width: '100%',
      padding: 16,
      borderRadius: 12,
      backgroundColor: '#fff',
      marginBottom: 20,
      shadowOpacity: 0.06,
      shadowRadius: 6,
    },
    calendarHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      paddingHorizontal: 6,
      marginBottom: 12,
    },
    calendarNavButton: {
      fontSize: 20,
      padding: 8,
      color: '#333',
    },
    calendarMonthYear: {
      fontSize: 18,
      fontWeight: '600',
      textAlign: 'center',
    },
    calendarGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      width: '100%',
    },
    calendarDayEmpty: {
      width: '14.2857%',
      aspectRatio: 1,
      padding: 6,
      marginBottom: 6,
    },
    calendarDay: {
      width: '14.2857%',
      aspectRatio: 1,
      padding: 6,
      marginBottom: 6,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      borderWidth: 1,
      borderColor: '#eee',
      backgroundColor: 'transparent',
    },
    calendarDaySelected: {
      backgroundColor: '#0d6efd',
      borderColor: '#0d6efd',
    },
    calendarDayToday: {
      borderColor: '#198754',
      borderWidth: 2,
    },
    calendarDayNumber: {
      fontSize: 14,
      fontWeight: '500',
    },
    cashflowIndicator: {
      marginTop: 6,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cashflowDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    selectedDateDetails: {
      marginTop: 14,
      padding: 12,
      backgroundColor: '#fff',
      borderRadius: 8,
      width: '100%',
    },
    selectedDateTitle: {
      fontSize: 18,
      fontWeight: '600',
      marginBottom: 8,
    },
    dayStats: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      paddingVertical: 8,
    },
    dayStatItem: {
      fontSize: 14,
      color: '#333',
    },
    dayTransactions: {
      marginTop: 8,
      width: '100%',
    },
    dayTransactionsTitle: {
      fontWeight: '600',
      marginBottom: 8,
    },
    transactionItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderColor: '#eee',
      paddingVertical: 8,
    },
    transactionDesc: {
      fontSize: 14,
      color: '#333',
    },
    
});